### ISSUE TITLE
Error academia

### ISSUE THREAD

**Issue by MenachoIvan** [midudev/midudev-issues#1]
Buenas Midu,

He estado mirando un poco el tema de midu.dev, y he entrado y me he suscrito con Prime ya que he visto que coin la suscripción prime debería tener acceso a la academia.

Resulta que cuando voy a la academia solo me sale el botón de suscribete, redirigiendome a Twitch y sin darme acceso a esta:
![image](https://github.com/user-attachments/assets/bab63498-d0ff-4b12-bd00-2307248c9579)

¿Es algo en lo que yo me he perdido o es un error de la web?

Saludos,

**Comment by GFrancV** [comment]
Buenas,

Ya revisaste este punto de las Preguntas frecuentes?

![image](https://github.com/user-attachments/assets/645341e9-42ca-4a1b-8f5f-45bc47cf059c)

**Comment by MenachoIvan** [comment]
Buenas,

Disculpa, se me había pasado.

Gracias por la respuesta :)

**Comment by MenachoIvan** [comment]
Acabo de revisar y tengo la cuenta verificada:

![image](https://github.com/user-attachments/assets/315b5b92-5917-4ab4-84e8-1f0a124ee050)

**Comment by maadeval** [comment]
Hola @MenachoRBB! 👋 Como estas?
Muchas gracias por reportar el issue!

Es un problema de UX que no queda claro como acceder a la academia, ya lo vamos a mejorar! 🙂 Ese botón de Suscribirse es solo para los usuarios que no estan suscritos, en tu caso que ya lo estás, no debería de aparecer.

Puedes probar de dar click a uno de estos dos botones que te comparto en la captura? Con esos podrás iniciar sesión y tener acceso!

👇

![CleanShot 2024-10-16 at 13 00 06@2x](https://github.com/user-attachments/assets/e5d21741-8880-446d-b51e-f5662fa23af9)

**Comment by MenachoIvan** [comment]
Buenas,

Teniendo iniciada sesión me sigue saliendo lo de suscribirse:

![imagen](https://github.com/user-attachments/assets/4cb0ecb5-5660-4214-afa1-e795ecdb9c5a)

Gracias!!

**Comment by maadeval** [comment]
Listo! ✅ Gracias por el feedback @MenachoRBB !

Mejoramos la UI para que no aparezca el botón de `Suscribete`
Y cambiamos la forma de mostrar los cursos 

Otra vez, gracias por tu tiempo en reportar estas cosas! Ayuda muchísimo a que lo hagamos mejor  :grin:

---

Queda pronto para cerrar la issue @midudev 

![CleanShot 2024-10-17 at 17 23 33@2x](https://github.com/user-attachments/assets/e9fb781e-9c50-490a-9576-67571f7a82f5)

**Comment by MenachoIvan** [comment]
Ya bien, muchas gracias!
